# Generated by Django 5.1.3 on 2024-11-13 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matematica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calcolo',
            name='tempo_calcolo',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
