# Generated by Django 5.1.3 on 2024-11-13 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matematica', '0002_calcolo_tempo_calcolo'),
    ]

    operations = [
        migrations.AddField(
            model_name='calcolo',
            name='variabile_dipendente',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='calcolo',
            name='variabili_sistema',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
