# Generated by Django 5.1.3 on 2024-11-15 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matematica', '0003_calcolo_variabile_dipendente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SteamReformerCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('espressione', models.CharField(max_length=200)),
                ('operazione', models.CharField(max_length=50)),
                ('portata_molare_idrocarburo', models.FloatField()),
                ('portata_molare_vapore', models.FloatField()),
                ('risultato', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
