# Generated by Django 5.1.3 on 2024-11-16 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matematica', '0004_steamreformercalculation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SteamReformerCalcolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portata_molare_idrocarburo', models.FloatField()),
                ('portata_molare_vapore', models.FloatField()),
                ('entalpia_prodotti', models.FloatField()),
                ('entalpia_reagenti', models.FloatField()),
                ('quantita_molare', models.FloatField()),
                ('rapporto_vapore_carbonio', models.CharField(max_length=100)),
                ('calore_di_reazione', models.CharField(max_length=100)),
                ('tempo_calcolo', models.FloatField()),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='SteamReformerCalculation',
        ),
        migrations.AlterField(
            model_name='calcolo',
            name='espressione',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='calcolo',
            name='operazione',
            field=models.CharField(max_length=100),
        ),
    ]
