# Generated by Django 5.1.3 on 2024-11-16 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matematica', '0005_steamreformercalcolo_delete_steamreformercalculation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steamreformercalcolo',
            name='calore_di_reazione',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='steamreformercalcolo',
            name='rapporto_vapore_carbonio',
            field=models.FloatField(),
        ),
    ]
